### ISSUE TITLE
请问最后一个文件上传问题?

### ISSUE THREAD

**Issue by yt7649757** [ruanyf/koa-demos#12]
curl是linux的命令，这里假如我模拟一个Post请求，请求本地的3000端口，，请求为files: 本地的文件的真是路径(例如C:\Users\xx\Desktop\koa-demos-master.zip), 

`const files = ctx.request.body.files || {} 就是直接拿到了  C:\Users\xx\Desktop\koa-demos-master.zip这个路径了，然后下面又是遍历，，结果下面 又对这个files遍历了`

`const` filePath = path.join(tmpdir,file.name)
file.name肯定会是undefined，然后文件肯定是不能上传，我想问的就是在windows上这个例子该怎么写啊?如何更好然后模拟测试呢?不知道怎么写?

**Comment by ruanyf** [comment]
参考这个链接，试试 ctx.request.files。

https://github.com/koajs/bodyparser/issues/94
