### ISSUE TITLE
build image时提示有错误

### ISSUE THREAD

**Issue by Xmaspro** [ruanyf/koa-demos#15]
运行环境：ARM VPS + ubuntu

运行 $ docker image build -t koa-demo . 之后，提出如下错误：
[Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

是否可以看下怎么解决，谢谢。

**Comment by ruanyf** [comment]
没研究过 arm64 架构
