### ISSUE TITLE
阮老师，demo4里面的路径会报错，改成“./template.html”才行。

### ISSUE THREAD

**Issue by colgin** [ruanyf/koa-demos#4]

**Comment by ruanyf** [comment]
我是在项目的根目录下执行，你进入了 `demos`目录了。

**Comment by LeonWuV** [comment]
根目录下执行命令是不是为 node demos/04.js   ；

您可以打印一下 __dirname  ，还是在demos的下面；

我认为不管你是在哪里执行，nodejs最后的位置一定是在被执行的文件所在的路径里；

所以我觉得需要改为 __dirname + '/template.html' 更加合理

如果说的不对，望阮老师指正，谢谢。
